device: 'cuda'
base_queries_path: 'data/ifeval_wo_instructions.jsonl'
data_no_instr_path: null
transformers_cache_dir: null

model_name: 'phi-3'
max_new_tokens: 2
num_final_tokens: 1
constraint_type: 'include'
keywords_set: 'ifeval_include'
n_examples: 10

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .