device: 'cuda'
project_dir: '/home/t-astolfo/t-astolfo/ifeval_experiments'
data_path: '../data/all_base_x_all_instructions_filtered.jsonl'
#data_no_instr_path: '../data/input_data_no_instr.jsonl'
data_no_instr_path: null
dry_run: False
output_path: 'out/'
path_to_hf_token: '../hf_token.txt'
transformers_cache_dir: null

model_name: 'gpt2'
max_new_tokens: 2
num_final_tokens: 2
constraint_type: 'sentences'
n_sent_max: 10
n_examples: 50

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .