device: 'cuda'
data_path: './data/ifeval_wo_instructions.jsonl'
dry_run: False
transformers_cache_dir: null

model_name: 'phi-3'
max_new_tokens: 2
num_final_tokens: 1
constraint_type: 'sentences'
n_sent_max: 10
n_examples: 50

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: . 