device: 'cuda'
project_dir: '/home/t-astolfo/t-astolfo/ifeval_experiments'
data_path: '../data/all_base_x_all_instructions_filtered.jsonl'
#data_no_instr_path: '../data/input_data_no_instr.jsonl'
data_no_instr_path: null
dry_run: False
output_path: 'out/'
path_to_hf_token: '../hf_token.txt'
transformers_cache_dir: /cluster/scratch/stolfoa/transformers_cache

model_name: 'phi-3'
max_new_tokens: 2
num_final_tokens: 1
constraint_type: 'include'
word_list: ['apple']
n_examples: 10

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .