device: 'cuda'
project_dir: '/home/t-astolfo/t-astolfo/composition'
data_path: '../data/input_data_multiple_instr_nonpar.jsonl'
dry_run: False
output_path: 'out/'
path_to_hf_token: '../hf_token.txt'
nonparametric_only: False

model_name: 'gpt2'
max_generation_length: 2048

steering: 'none'
source_layer_idx: 20
apply_to_all_layers: False
steering_weight: 1.0
representations_folder: 'single_instr_all_base_x_all_instr'
include_instructions: True



defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .