device: 'cuda'
project_dir: '/home/t-astolfo/t-astolfo/ifeval_experiments'
data_path: '../data/all_base_x_all_instructions_filtered.jsonl'
dry_run: False
output_path: 'layer_search_out/'
path_to_hf_token: '../hf_token.txt'
nonparametric_only: False

model_name: 'phi-3'
max_generation_length: 768
n_examples_per_instruction: 10
include_instruction: True
specific_instruction: null
cross_model_steering: False

seed: 42
steering: 'adjust_rs'
steering_weight: 1.0
representations_folder: 'single_instr_all_base_x_all_instr'




defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .