device: 'cuda'
data_path: './data/keyword_validation.jsonl'
dry_run: False
output_path: 'layer_search_out'
transformers_cache_dir: null

model_name: 'phi-3'
steering: 'add_vector'
steering_weights: [100]

include_instruction: True
constraint: 'exclude'

n_examples: 20
max_generation_length: 768
n_examples_per_instruction: 10
seed: 42


defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .