device: 'cuda'
data_path: './data/all_base_x_all_instructions_filtered.jsonl'
output_path: './ifeval_experiments/layer_search_out/'
dry_run: False

model_name: 'phi-3'
max_generation_length: 768
n_examples_per_instruction: 10

include_instruction: True
specific_instruction: null
cross_model_steering: False

transformers_cache_dir: null

seed: 42
steering: 'adjust_rs'
steering_weight: 1.0
representations_folder: 'single_instr_all_base_x_all_instr'


defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .