device: 'cuda'
data_path: 'data/input_data_single_instr.jsonl'
dry_run: False
output_path: 'out'
transformers_cache_dir: null

model_name: 'phi-3'
max_generation_length: 1024

specific_instruction: 'forbidden'
include_instructions: True

steering: 'none'
source_layer_idx: 24
steering_weight: 0.0
n_examples: 10
representations_folder: 'representations'


defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .