device: 'cuda'
data_path: './data/ifeval_wo_instructions.jsonl'
dry_run: False
output_path: 'out'
path_to_hf_token: './hf_token.txt'
transformers_cache_dir: /cluster/scratch/stolfoa/transformers_cache


model_name: 'phi-3'
max_generation_length: 1024

include_instructions: False
n_sent_max: 5
constraint_type: at_most
n_examples: 50
steering_weights: [1]
length_rep_file: high_level_50examples_hs.h5


steering: 'none'
source_layer_idx: 12
representations_folder: 'representations'



defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .