device: 'cuda'
project_dir: '/home/t-astolfo/t-astolfo/composition'
data_path: '../data/input_data_single_instr.jsonl'
dry_run: False
output_path: 'nonpar_plus_length_out/'
path_to_hf_token: '../hf_token.txt'
nonparametric_only: True
seed: 42
include_instructions: True

model_name: 'phi-3'
max_generation_length: 2048
n_sent_max: 5

steering: 'none'
source_layer_idx: 20
steering_weight: 1.0
representations_folder: 'single_instr_all_base_x_all_instr'

include_length_instr: True
length_steering: 'conciseness'
length_steering_weight: 20
length_source_layer_idx: 12
constraint_type: at_most
length_representations_folder: '../length_constraints/representations'
length_rep_file: high_level_50examples_hs.h5



use_data_subset: False
data_subset_ratio: 0.7
specific_instruction: null



defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .