device: 'cuda'
data_path: 'data/format/all_base_x_all_instructions_filtered.jsonl'
dry_run: False
transformers_cache_dir: null

model_name: 'phi-3'
max_generation_length: 2 # increase to check model's outputs, decrease for faster computation
num_final_tokens: 1
use_data_subset: False
data_subset_ratio: 0.7

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .