device: 'cuda'
data_path: './data/input_data_single_instr.jsonl'
dry_run: False
output_path: 'out/'
transformers_cache_dir: null

model_name: 'phi-3'
max_generation_length: 2048
hf_model: True
cross_model_steering: False

steering: 'none'
source_layer_idx: 20
steering_weight: 1.0
representations_folder: 'single_instr_all_base_x_all_instr'



defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .